databases:
    - name: formlydb
      plan: free
      databaseName: formlydb
      user: formly

services:
    - type: web
      plan: free
      name: Formly
      runtime: python
      buildCommand: './build.sh'
      startCommand: 'gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker'
      envVars:
        - key : DATABASE_URL
          fromDatabase:
            name: formlydb
            property: connectionString
          
        - key: SECRET_KEY

          generateValue: true

        - key: WEB_CONCURRENCY

          value: 4
      

